apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helm-template
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/GwynHannay/helm-template
  ref:
    branch: "old-version"
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: common
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/library/common
      sourceRef:
        kind: GitRepository
        name: helm-template
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-template
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/other/app-template
      sourceRef:
        kind: GitRepository
        name: helm-template
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2