---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "${NAS_HOST}"
    path: "/mypool/kubernetes/vols/paperless"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: nfs-paperless
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-paperless
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/tera/vols/paperless
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - iris
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-paperless
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: local-paperless