---
apiVersion: v1
kind: ConfigMap
metadata:
  name: readeck-config
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: readeck
data:
  TZ: "Australia/Perth"

  # App
  READECK_LOG_LEVEL: info
  READECK_SERVER_HOST: "0.0.0.0"
  READECK_SERVER_PORT: "8080"
  READECK_SERVER_PREFIX: "/"
  READECK_USE_X_FORWARDED: "true"
