---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app wallabag
  namespace: &ns self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1002
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        containers:
          main:
            dependsOn:
              - postgresql
              - redis
            image:
              repository: wallabag/wallabag
              tag: 2.6.9
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: &secrets wallabag-secrets
              - configMapRef:
                  name: &config wallabag-config
          
          postgresql:
            name: postgresql
            image:
              repository: docker.io/library/postgres
              tag: 16.1
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config
            securityContext:
              runAsUser: 999
              allowPrivilegeEscalation: false
          
          redis:
            name: redis
            image:
              repository: docker.io/library/redis
              tag: 7
              pullPolicy: IfNotPresent

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Bookmarked Articles
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: wallabag.png
          gethomepage.dev/name: Wallabag
        hosts:
          - host: &host "wallabag.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      images:
        existingClaim: local-wallabag
        advancedMounts:
          main:
            main:
              - path: /var/www/wallabag/web/assets/images
                subPath: images
            postgresql:
              - path: /var/lib/postgresql/data
                subPath: pgdata
