---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-glances
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-glances
  namespace: system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: host-glances
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-glances
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "${NAS_HOST}"
    path: "/mypool/kubernetes/vols"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-glances
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-glances