---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-glances
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /home
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - elite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-glances
  namespace: system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: host-glances
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tera-glances
spec:
  capacity:
    storage: 920Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/tera
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - elite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tera-glances
  namespace: system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 920Gi
  volumeName: tera-glances
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-glances
spec:
  capacity:
    storage: 1020Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/nas
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - elite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-glances
  namespace: system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1020Gi
  volumeName: nas-glances