---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./glances-app.yaml
  - ./glances-pvc.yaml
configMapGenerator:
  - name: glances
    files:
      - glances.conf
generatorOptions:
  disableNameSuffixHash: true