---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-joplin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "${NAS_HOST}"
    path: "/mypool/kubernetes/vols/joplin"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-joplin
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-joplin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-joplin
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/tera/vols/joplin
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - elite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-joplin
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  volumeName: local-joplin