apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:6cXyCQVO0PENzesNzUxPYJY=,iv:tz7TXUbMebMu69T+TbeUQPCoECNqzct4dGGAY5LqhvM=,tag:bTJ8S6mTig05WL8RsaBzJg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:nIKbKYjDUNRy8Q==,iv:ITRvyC8ovG0/leMoBbJ43zlxPpcuy+xKpugie2I80MU=,tag:wxajaNm+NfrwdERus1DqCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c2t2cGlic1JQUllxQi9X
            L1NIb2VIS0VHR2twYkVHa1ZDNjYwaDNJZUdRCms1UWFWcnIyV2tibXVWZHhpc1pG
            RCtDQmxjZFl3MTVxcVE0SW1HM1lyUzAKLS0tIHpIeUM2NXl0L2xuS3pjazZjR3Qz
            TExnYXJsV0ZnQkU0U0xhZmdhQ3pJZlEKlgGP+meKHJF50eQtDnsGy71R6h4mXQ7R
            TXuQ9Ri2b4qmiz3Y6T6Rk27lWsNuGcAHZpmPJgwl/x+R7fnzSG8i6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T21:36:58Z"
    mac: ENC[AES256_GCM,data:VOpn3Q9bUxHWCGCENdR1WnGlvERNJ51MCTGkovXHNpVltWHd8HqEjPrhqvW8k2G0hoeL3osEsmcQFYrIfPgfptqY+pX+mJs9O+xLG/V6+g/QdTde9cxBF1+d+HwdndazoeXszZfvJ7Ge1otJGbARLFA0me7Ig2iV8nWBvv7OTYY=,iv:nl7Lm4PMx4iQ1VWzRkno8SzuIfkBtMB3N7IK6ieuy7c=,tag:GBbRfMWBPkLdcZ/9edYGqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:rsoXscMgjBT5wv2jO9FDctOz3Of5S/2W+Ij4K841qfemm6k2eboPQQ==,iv:jLxlvIf9a3Qh9DnIeATsPfH6nMyqjVE5PWw5JW8MZTA=,tag:8L4UU32Tph5GvilSmf1RZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c2t2cGlic1JQUllxQi9X
            L1NIb2VIS0VHR2twYkVHa1ZDNjYwaDNJZUdRCms1UWFWcnIyV2tibXVWZHhpc1pG
            RCtDQmxjZFl3MTVxcVE0SW1HM1lyUzAKLS0tIHpIeUM2NXl0L2xuS3pjazZjR3Qz
            TExnYXJsV0ZnQkU0U0xhZmdhQ3pJZlEKlgGP+meKHJF50eQtDnsGy71R6h4mXQ7R
            TXuQ9Ri2b4qmiz3Y6T6Rk27lWsNuGcAHZpmPJgwl/x+R7fnzSG8i6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T21:36:58Z"
    mac: ENC[AES256_GCM,data:VOpn3Q9bUxHWCGCENdR1WnGlvERNJ51MCTGkovXHNpVltWHd8HqEjPrhqvW8k2G0hoeL3osEsmcQFYrIfPgfptqY+pX+mJs9O+xLG/V6+g/QdTde9cxBF1+d+HwdndazoeXszZfvJ7Ge1otJGbARLFA0me7Ig2iV8nWBvv7OTYY=,iv:nl7Lm4PMx4iQ1VWzRkno8SzuIfkBtMB3N7IK6ieuy7c=,tag:GBbRfMWBPkLdcZ/9edYGqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
