apiVersion: v1
kind: Secret
metadata:
    name: staging-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:6cXyCQVO0PENzesNzUxPYJY=,iv:tz7TXUbMebMu69T+TbeUQPCoECNqzct4dGGAY5LqhvM=,tag:bTJ8S6mTig05WL8RsaBzJg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:nIKbKYjDUNRy8Q==,iv:ITRvyC8ovG0/leMoBbJ43zlxPpcuy+xKpugie2I80MU=,tag:wxajaNm+NfrwdERus1DqCQ==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:PIrMJZkvGfi4ZN3qAil1JaBtUD5n6P1a8gWUH4QQMBWTXRlMb2uPKw==,iv:y/jYWBJrSaIZJfsNro++siy0LjkGS1o9YBvsSS8Kl6E=,tag:mtixRmZ1OtIfpVbza3qU/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c2t2cGlic1JQUllxQi9X
            L1NIb2VIS0VHR2twYkVHa1ZDNjYwaDNJZUdRCms1UWFWcnIyV2tibXVWZHhpc1pG
            RCtDQmxjZFl3MTVxcVE0SW1HM1lyUzAKLS0tIHpIeUM2NXl0L2xuS3pjazZjR3Qz
            TExnYXJsV0ZnQkU0U0xhZmdhQ3pJZlEKlgGP+meKHJF50eQtDnsGy71R6h4mXQ7R
            TXuQ9Ri2b4qmiz3Y6T6Rk27lWsNuGcAHZpmPJgwl/x+R7fnzSG8i6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T23:42:32Z"
    mac: ENC[AES256_GCM,data:8R8a8E6hDbdrRy/+i6aSQ3BhLN4GQ/kVoVMPWhL94lflhe7OEe4IDs5HJYbmwQuNwB/Ztrcvs/4mm2tdVhWfXidjB+Ef1Xupy3M0tD89nvXeuy1C4UBAfZtoEsY7rP6JmXXqhFQzvEgZeltQaa4PfvGrTrpv8jOBrkLkvET9Jww=,iv:NDC4oAPmegUbANnAHGGXjWRHClIQaXxx8jMFV3ePEsU=,tag:7F4KddU01CzrLNP2Em2t8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c2t2cGlic1JQUllxQi9X
            L1NIb2VIS0VHR2twYkVHa1ZDNjYwaDNJZUdRCms1UWFWcnIyV2tibXVWZHhpc1pG
            RCtDQmxjZFl3MTVxcVE0SW1HM1lyUzAKLS0tIHpIeUM2NXl0L2xuS3pjazZjR3Qz
            TExnYXJsV0ZnQkU0U0xhZmdhQ3pJZlEKlgGP+meKHJF50eQtDnsGy71R6h4mXQ7R
            TXuQ9Ri2b4qmiz3Y6T6Rk27lWsNuGcAHZpmPJgwl/x+R7fnzSG8i6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T23:42:32Z"
    mac: ENC[AES256_GCM,data:8R8a8E6hDbdrRy/+i6aSQ3BhLN4GQ/kVoVMPWhL94lflhe7OEe4IDs5HJYbmwQuNwB/Ztrcvs/4mm2tdVhWfXidjB+Ef1Xupy3M0tD89nvXeuy1C4UBAfZtoEsY7rP6JmXXqhFQzvEgZeltQaa4PfvGrTrpv8jOBrkLkvET9Jww=,iv:NDC4oAPmegUbANnAHGGXjWRHClIQaXxx8jMFV3ePEsU=,tag:7F4KddU01CzrLNP2Em2t8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
