apiVersion: v1
kind: Secret
metadata:
    name: staging-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:S/Xtc8Nok3ZHatlm2+U4cjs=,iv:yWgja8Vkk1S3jXMyng76eBoiziXq6FQ5NG6zB0OzrWI=,tag:TAbSo0t7M+rIS5wHmRNqPg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:3z8uIp9YpcUxvw==,iv:fPSJpl35IXKVh04P3bhztoeDe6fxGs11sIaiNzyynQQ=,tag:sf0hrMtcu8HGx7vSYeT4Vw==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:JvH22zVw71eH9wq0CrW7U1fu/8T922XSXOWkOghjOuM73F0e+nc0EQ==,iv:UOEpOE8TB+WQhYIjoq3tFoLfm1bS96GC1fGI3QeyhDE=,tag:11tCp5UFH6TQ1PpSFSRbgQ==,type:str]
    IP_RANGE: ENC[AES256_GCM,data:Z8NNqaTSYsbVNkWhpjWOSQW2AnAwhDH/Yw==,iv:aUk2M9mqhM9SVa/rpOz7eTIT/4OQPOIVKnU7yW/M39g=,tag:mjDjNFnEgjAbByyYhc6C/A==,type:str]
    INGRESS_IP: ENC[AES256_GCM,data:bnSQwrBmLY6fYGQk,iv:pdxXYxIGP7r/8YsiNtCLWKGgCSxmZF0wrrM1iW/GR6k=,tag:ZAmGNhPc02Iuc8P1etGCZw==,type:str]
    INGRESS_HOST: ENC[AES256_GCM,data:oCXFACZCWeqpP2+jec11gN2rVQ6IbB8=,iv:4eaohckZ0PKrA/1KSOot/aFiT4k0cq594acVN2cyOyw=,tag:rDlvHrKLKqmzsJbKUZqNXA==,type:str]
    NAS_HOST: ENC[AES256_GCM,data:Nh43+0IT/XLmMos=,iv:6AZzkkRig2rvKFl2/kRMDBirqnzWQgzOoBddPbt4Akw=,tag:kZVK2Bln2NdO0UxZYm7VwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeFExbkVSbDhTMkxjS0c3
            TVd2Q1lNZmFCdWswUDh5Z1I5ZTh4Z3FwMGpBCkdQOVBBM2lGZ2NPN29XUTBwSFlh
            ZlBycFFQbzRxaExnRVhNU3Y1MVJ0b1UKLS0tIFBCRUFWKytYZGVTSGIyeTBaNkZ0
            akRaUlpFL2lyZ0VGMkRiVnp5dS9DSGMKjBVdW9wqONDkaoortRsk7cY4XITIFHqw
            19Tj1wtpsk8BFxw0oMGb+XXgsVowVXKawow5YQsen4AbixuGSQwr8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T22:19:01Z"
    mac: ENC[AES256_GCM,data:aLi8QvqplcLvAB9i+S+YMnV36Zg7MgkfHoGs9lYtjlyTHd3OQvhWFtcBDqBfhPf8rK4vZNApip4+m4OnIrPNGvX/58q7P387NbGfkDKIAlzdw2K4VN8kDN/EqSHUdp/7UaJHLnf6+u3O31JkzIqdVXDpUjeenD7Qko4KZBqpETc=,iv:jivhocb4xED7lOsTd3oFeVeHwqZ6yf+xNOBzzFi7+98=,tag:3tyWY3ERM7YJdBzh8eX8bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
