---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./namespace.yaml
  - ./calibre/calibre-pvc.yaml
  # - ./calibre/calibre-app.yaml
  - ./calibre/calibre-web.yaml
  - ./immich/immich-pvc.yaml
  - ./immich/immich-config.yaml
  - ./immich/immich-secrets.sops.yaml
  - ./immich/immich-app.yaml
  - ./paperless/paperless-pvc.yaml
  - ./paperless/paperless-config.yaml
  - ./paperless/paperless-secrets.sops.yaml
  - ./paperless/paperless-app.yaml