---
creation_rules:
  - path_regex: kubernetes/apps/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu"
  
  - path_regex: kubernetes/infrastructure/.*\.ya?ml
    encrypted_regex: "^(email|dnsZones)$"
    key_groups:
      - age:
          - "age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu"