---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emberstack
  namespace: kube-system
spec:
  interval: 24h
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-replicator
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: kube-system
      interval: 12h
---