---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1002
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        containers:
          main:
            image:
              repository: dpage/pgadmin4
              tag: 8.13
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: &secrets pgadmin-secrets
          
          postgresql:
            name: postgresql
            image:
              repository: docker.io/library/postgres
              tag: 16.1
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: *secrets
            securityContext:
              runAsUser: 999
              allowPrivilegeEscalation: false

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: PostgreSQL GUI
          gethomepage.dev/group: data
          gethomepage.dev/icon: pgadmin.png
          gethomepage.dev/name: pgAdmin
        hosts:
          - host: &host "pgadmin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: local-pgadmin
        globalMounts:
          - path: /var/lib/pgadmin
      db:
        enabled: true
        existingClaim: local-pgadmindb
        advancedMounts:
          main:
            postgresql:
              - path: /var/lib/postgresql/data
                subPath: pgdata
        
