apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: storage
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:Bv5dpbrQpJkMx9EmTinInD0=,iv:Mz6svAhu41Xj4pygqMULS3vejmsXXoRCyq6NiKu5gk8=,tag:ekxIw93FTTHIAoPLf5hohQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:zT4zzL+4lsCbYaCCiJBOSRLE1CU=,iv:sSVzba5mKbBXUr3ow5KSyRRDEGFqqJ6qs2iwjhLSXQg=,tag:MwpiB1MnTJey74KprXHVgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aFZQbkRJeGpqUklGVGcw
            Z1p5MCtqWFZibzFyYnc0dWx1cHZGZGZaLzF3CjlLdmN0cGZ3Y1kzeGxpekl3STJQ
            bFhxcTlSeVF2dnI5QTlCVnJLWEVHZjAKLS0tIDR2UVJSc3BZVHdNWitPVzVNWWZC
            b2R1SHpyUEVvUkQ5VDI4WjBwandJdFEKAo4FwoQbT92B0OwJGzS0s+9VOh1D1yQE
            rs4X+O7gL9bqFg8Yj+b0lKn9ONb4p87Kxf/kZ1KwT7+IP93jbE6fMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T22:15:02Z"
    mac: ENC[AES256_GCM,data:14lLZTGUKn5YQCEr5b49vGB0htOi1/yAq6Pyl7FHir9HSny4AmXH40np9wnGZVZa/Oz4LkF2X4KI83rGItsyzyqbpN7a88RNc7SZT7Mtt5QTIyCGPkV0g1fK1AvkUgn+QJjmNVC35ZAfaN40KYBkN4CMJCV06pVcSfRfUgKeDaM=,iv:aFi49X9YH/+TCv3MAuV1M1LLqqwr45rAixT+f0uGX4Y=,tag:1bsQJYlD0Th3GwN2YTeJfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
