apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: storage
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:Bv5dpbrQpJkMx9EmTinInD0=,iv:Mz6svAhu41Xj4pygqMULS3vejmsXXoRCyq6NiKu5gk8=,tag:ekxIw93FTTHIAoPLf5hohQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:zT4zzL+4lsCbYaCCiJBOSRLE1CU=,iv:sSVzba5mKbBXUr3ow5KSyRRDEGFqqJ6qs2iwjhLSXQg=,tag:MwpiB1MnTJey74KprXHVgA==,type:str]
    #ENC[AES256_GCM,data:OOxweme1Vu0=,iv:i0n259uG47ZR30t2Xwg3/mS68QgHFQd/+VoL6W8qXkA=,tag:dvtOUAzHgtOwoAW4zZgmhQ==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:by6La2KTXg==,iv:2xH3qHnLc4EdE9l0ppCCZH3USrzJmni6nFmejex9xf0=,tag:Sct6+oDDVGRuFIzSGC057w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:RW5zq8c7l9KHzDCn0A==,iv:N6/fv3A39dxAN/ba9e6Hsts8EtpEbJ1Toah0jfE5+Lg=,tag:S6Lubl7U6bgnGxn5++Hv2A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:q7k+VnAy3FNBKcN5tvuafTxoFzU=,iv:cWCJeGVOC5M0S+BOs4h40MJDctT/SjHcFQI7YjmO2gA=,tag:nt343jGn6yir/5yE6g56ZA==,type:str]
sops:
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aFZQbkRJeGpqUklGVGcw
            Z1p5MCtqWFZibzFyYnc0dWx1cHZGZGZaLzF3CjlLdmN0cGZ3Y1kzeGxpekl3STJQ
            bFhxcTlSeVF2dnI5QTlCVnJLWEVHZjAKLS0tIDR2UVJSc3BZVHdNWitPVzVNWWZC
            b2R1SHpyUEVvUkQ5VDI4WjBwandJdFEKAo4FwoQbT92B0OwJGzS0s+9VOh1D1yQE
            rs4X+O7gL9bqFg8Yj+b0lKn9ONb4p87Kxf/kZ1KwT7+IP93jbE6fMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T21:20:44Z"
    mac: ENC[AES256_GCM,data:/2tfcu0DrdDN4PwO8W28y4VNhYy8q+zO0CsHrk0sC7qcrnC4Txi1tLEbfWGAk9R3kZoOFFSOgAfgbH7otjRYLf77q5mx8sjBc5R6xHloUBfroM7ZESL0xNhxkiZRtaxtsJNLRbB4l9S/+n7JwvLQxee/4rzluOBWijXyqipl++U=,iv:a+hog0MlCENe+oTWegIJvpvhad8LMHFdstnRlAYUtoU=,tag:R8yjX5ZYAed3SOU+Exf39A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
