---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "${NAS_HOST}"
    path: "/mypool/kubernetes/vols/immich"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-immich
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: nfs-immich