---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ghostfolio-config
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: ghostfolio
data:
  REDIS_HOST: ghostfolio-redis.self-hosted
  REDIS_PORT: "6379"
  POSTGRES_DB: ghostfolio