apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secrets
    namespace: self-hosted
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:tYBWW5YDfTbS7j0UCwtUaCtp0vg5G0Kjqg==,iv:lr9PIx1f4R9rASyBy5Uvwb8Xc0QV+2IcOVBaVLWPvaY=,tag:cQRAVj/RCCysVmIQ29eEAw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:YDZHUYoi,iv:1MQQ/FjNjDa+TPPDXMc7msN+1I795uXpYazzzM/BZBI=,tag:ScJyHkAkv+JYxiwVpPP6jw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:zH4kVYbm+lvV4487ITGHiheeEVVATxytpMehyc4=,iv:u6i5nKy/nfi7sNQObASyp1nAFwT/TVhEKLduaA9vMOA=,tag:QqhTVFsZPrk8mLca8EAhNQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Jv0HszlPQITIk1211Hun125mgHWIqdH5jPi8sgpqjz2bHAp7zZJyNt1oviApf3LUc+8xAzPHCjRojQzl5tVT7SU2/omqxw1xj9BrTL20iNXqs7FAn3cFnu7G7/Iyg851qEJwltdOu6YNciq1uMC0Rql0PdOF2ePVC0Oscf3EhqO1rJuo,iv:oAI9Jx2LE+jTvD6tQtYi6MbTDXUmjIqgaDjeSBhZqGw=,tag:sjLbFn2RCqA41aLulOkYeA==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:lSWI3w/KvnSNScldEG152zxd71GcwDIkQw==,iv:mChRLBBdwVngDlCzzC+qQnPaDeDX72VPQMOGZmN4+SU=,tag:yCSMIumNYiAF59I++h1lPw==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:y8gZrVmmoTGtmxdvzcQma/Wvm6UV93X61Q==,iv:4beirVAyBT6nJFSb6T0kPYE+PQK5aH4VV0ZytxPz4NM=,tag:7m+kban0qnxoaFOeLu6N0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y0RnZ21YZkFsTlEyRnEx
            dG1iOWJKMjZjUWNHdWR5SzFqbnIyVDlpd3c4CjlLREZqVUhXcHpYYWovTVZOLzJj
            UWhxVG12Rmg5ZzFHTlI1TkZYQkdQZk0KLS0tIHZHOVZYS1plSXJ5b0ZsNWZQQytr
            TDJwcmZJaTZKUENtNTZGcE8vTG5PMFEKfM2OSuwOXYt6Js76YtRP09xb7moQ3asN
            E5161ORRGJBxSK2TRHmcMvqu5ujDjPJdSyJuWiAAGLM7x2c7xvKNBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T01:30:08Z"
    mac: ENC[AES256_GCM,data:dCbcNjLqOkp2ZNk7Cxjl6/Vg6e1CNXJHLLADlwiTcOL3jTyDBgBncIymkn5ZiLzpU2a5r1MNJZ74c3UoO5B+vUdMD2KchZZXvz4bf2aDy/fQcuBRzD26kJMVdskkdH/DlZemY4AY+3Utzx1qbTGC9mSOMdzhGQc9wXkOnnuX/JE=,iv:GoyaYyC1ulwUZ1OGkt5y5gElny6uU3XCZ6XNdAO4U7M=,tag:RVMQmfgr2F2Ebf3zRWcPig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
