apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secrets
    namespace: self-hosted
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:tYBWW5YDfTbS7j0UCwtUaCtp0vg5G0Kjqg==,iv:lr9PIx1f4R9rASyBy5Uvwb8Xc0QV+2IcOVBaVLWPvaY=,tag:cQRAVj/RCCysVmIQ29eEAw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:YDZHUYoi,iv:1MQQ/FjNjDa+TPPDXMc7msN+1I795uXpYazzzM/BZBI=,tag:ScJyHkAkv+JYxiwVpPP6jw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:zH4kVYbm+lvV4487ITGHiheeEVVATxytpMehyc4=,iv:u6i5nKy/nfi7sNQObASyp1nAFwT/TVhEKLduaA9vMOA=,tag:QqhTVFsZPrk8mLca8EAhNQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:BUFHuOlYFGFvCHRIYfirwZTtuhiVTgN02T60ChepWOwSqjV0mPPHl2FEWJOjs8d6j2o/JLtR39P9octCSveF4cKS9uihycJAOAXT9Hwp2c2ZjqoKdfbgmuKj1+ILvWQGmuG3Ud57YQRuEKBSOSqIdxKfMZqomFcpHEDiS8Cxm1CxUy2QUKhmW2PTk2jBde0veB2Y8Sdi,iv:8RYsbQg0/bib9MvxEnEx20jPZqONTIk8PkWpiupdiYg=,tag:/wm8hvbXQZ45vZpeAAhPrg==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:lSWI3w/KvnSNScldEG152zxd71GcwDIkQw==,iv:mChRLBBdwVngDlCzzC+qQnPaDeDX72VPQMOGZmN4+SU=,tag:yCSMIumNYiAF59I++h1lPw==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:y8gZrVmmoTGtmxdvzcQma/Wvm6UV93X61Q==,iv:4beirVAyBT6nJFSb6T0kPYE+PQK5aH4VV0ZytxPz4NM=,tag:7m+kban0qnxoaFOeLu6N0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y0RnZ21YZkFsTlEyRnEx
            dG1iOWJKMjZjUWNHdWR5SzFqbnIyVDlpd3c4CjlLREZqVUhXcHpYYWovTVZOLzJj
            UWhxVG12Rmg5ZzFHTlI1TkZYQkdQZk0KLS0tIHZHOVZYS1plSXJ5b0ZsNWZQQytr
            TDJwcmZJaTZKUENtNTZGcE8vTG5PMFEKfM2OSuwOXYt6Js76YtRP09xb7moQ3asN
            E5161ORRGJBxSK2TRHmcMvqu5ujDjPJdSyJuWiAAGLM7x2c7xvKNBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T01:22:13Z"
    mac: ENC[AES256_GCM,data:59CkEyEBg6OjDcHzCsaNAY3yJjSQUVyM2GefpDGdhhSEdYIzNpb1pRb0DZrYEIcXuqCRfr6oywIEZOQAM360bKAS42xoEHpIEq1PGJUxd+bksVnq9GyrKbnOyGKjNM6BkiyHm5khw5iFUD9W2pQyTEAPTL8MdMf6Hx6sIAvv8M0=,iv:T5cYdlIMjkZ6eXp1Q3mURf4jHp1tKB8KJbJ4x+Q2sNc=,tag:D4V2XQsiNlhr9FZzEhNzKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
