---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghostfolio-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "${NAS_HOST}"
    path: "/mypool/kubernetes/vols"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghostfolio-nfs
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs