---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app ghostfolio
  namespace: &ns self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1002

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghostfolio/ghostfolio
              tag: 2.125.0
            envFrom:
              - secretRef:
                  name: &secrets ghostfolio-secrets
              - configMapRef:
                  name: &config ghostfolio-config
          
          postgres:
            image: 
              repository: docker.io/library/postgres
              tag: 15
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config
          
          redis:
            image:
              repository: docker.io/library/redis
              tag: alpine
            command: ['redis-server', '--requirepass', "$(REDIS_PASSWORD)"]
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config

    service:
      main:
        ports:
          http:
            port: 3333

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Finance Dashboard
          gethomepage.dev/group: widgets
          gethomepage.dev/icon: ghostfolio.png
          gethomepage.dev/name: Ghostfolio
          gethomepage.dev/widget.type: ghostfolio
          gethomepage.dev/widget.url: "https://ghost-snap.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_GHOSTFOLIO}}"
        hosts:
          - host: &host "ghost-snap.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls: []
