# ---
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: calibre-web
#   namespace: media
# spec:
#   endpoints:
#   - dnsName: "books-snap.${SECRET_DOMAIN}"
#     recordTTL: 180
#     recordType: CNAME
#     targets:
#     - "${INGRESS_HOST}"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app calibre-web
  namespace: &ns media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1002
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/calibre-web
              tag: 0.6.21-ls240

    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: eBook Browser
          gethomepage.dev/group: widgets
          gethomepage.dev/icon: calibre-web.png
          gethomepage.dev/name: Calibre Web
          gethomepage.dev/weight: "15"
          gethomepage.dev/widget.type: calibreweb
          gethomepage.dev/widget.url: "https://books-snap.${SECRET_DOMAIN}"
          gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_CALIBRE_USER}}"
          gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_CALIBRE_PASS}}"
          gethomepage.dev/widget.fields: '["books", "authors", "series"]'
        hosts:
          - host: &host "books-snap.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls: []

    persistence:
      config:
        enabled: true
        existingClaim: nfs
        globalMounts:
          - path: /config
            subPath: calibre/web
          - path: /books
            subPath: calibre/library
