---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ./namespace.yaml
  - ./gphotos/gphotos-pvc.yaml
  # - ./gphotos/gphotos-config.yaml
  # - ./gphotos/chrome-app.yaml
  # - ./gphotos/gphotos-app.yaml