---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
resources:
  - ./namespace.yaml
  - ./ghostfolio/ghostfolio.yaml
  - ./ghostfolio/ghostfolio-config.yaml
  - ./ghostfolio/ghostfolio-secrets.sops.yaml
  - ./homepage/homepage.yaml
  - ./homepage/homepage-secrets.sops.yaml
configMapGenerator:
  - name: homepage-gen-config
    files:
      - bookmarks.yaml=./homepage/config-maps/homepage-bookmarks.yaml
      - docker.yaml=./homepage/config-maps/homepage-docker.yaml
      - kubernetes.yaml=./homepage/config-maps/homepage-kubernetes.yaml
      - services.yaml=./homepage/config-maps/homepage-services.yaml
      - settings.yaml=./homepage/config-maps/homepage-settings.yaml
      - widgets.yaml=./homepage/config-maps/homepage-widgets.yaml
secretGenerator:
  - name: homepage-gen-secrets
    files:
      - values.yaml=./homepage/homepage-secrets.sops.yaml
configurations:
  - ./kustomizeconfig.yaml