---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: address-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.172.90.80-10.172.90.90
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: address-pool
  namespace: metallb-system