apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:BVtPF+PAqgPDV4WTfi2F+nvcYV2nqGcn4mHYQaE/Tnf6tci99SXODw==,iv:Gp1ML59KN/JPj+UCtp5InSZrcE5ASz1a9xHofc8Fn8M=,tag:Cdc4YGeDDOi3BOfS7tdo5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdmduK2IxOVhhaVEyNnpt
            dVMwdXpuMktDMU5KTnNoT09jWEVrZGN2b1JjCnA0Q3hySHk2amlOTnI5VzVoazF1
            eGFWVVJGYkhlK05kdjZJc1JIM3ppUFEKLS0tIHU1am84YkErN0RRdVVkd0FXRmRl
            ZTdzWkk4SjhFSFJtRDdPdTduemV6bTgK/umW8zYJtaWB3jYzIdcILv231BfsQLXk
            Ke3JbcAw/y/u5tW2V76wBPXIpJ2kcyZxo0AT6JmMc5s3EHmH9fSE2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T23:43:24Z"
    mac: ENC[AES256_GCM,data:5/3XHY/54AGALd73PqPGRxsQi3541kcwUMK/Vm5tseAAXoRJK57hRzRCSUSwg/VNyUlLD/grlVW3Q9eQyhAZ6qD5zcPz8/RuqoS8spR4Ygjeyg4Zdi+ceXSgr6eW5FVmF3iZ6J/W247SSU/poPPjthka25pfKfz5YBBtKsh1lQM=,iv:dBWBeKsCp7FW4/CSsEX9YGB3JddHgMKBThl+Iza2mEs=,tag:vrvByGKQ6+8IyMJ3KUJ9YQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: external-dns
stringData:
    api-token: ENC[AES256_GCM,data:dZxEiCM9FKwTNzkBMn0Lr/59XCiRLBfAJHGirvt7LLNT6mfVHL0O+A==,iv:AdfgzMyiig9ly4uvO65BhU6SmZqw41YxQZ1MTgh2x7k=,tag:vAm6/+8v2ZNRttR1OOPw0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdmduK2IxOVhhaVEyNnpt
            dVMwdXpuMktDMU5KTnNoT09jWEVrZGN2b1JjCnA0Q3hySHk2amlOTnI5VzVoazF1
            eGFWVVJGYkhlK05kdjZJc1JIM3ppUFEKLS0tIHU1am84YkErN0RRdVVkd0FXRmRl
            ZTdzWkk4SjhFSFJtRDdPdTduemV6bTgK/umW8zYJtaWB3jYzIdcILv231BfsQLXk
            Ke3JbcAw/y/u5tW2V76wBPXIpJ2kcyZxo0AT6JmMc5s3EHmH9fSE2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-19T23:43:24Z"
    mac: ENC[AES256_GCM,data:5/3XHY/54AGALd73PqPGRxsQi3541kcwUMK/Vm5tseAAXoRJK57hRzRCSUSwg/VNyUlLD/grlVW3Q9eQyhAZ6qD5zcPz8/RuqoS8spR4Ygjeyg4Zdi+ceXSgr6eW5FVmF3iZ6J/W247SSU/poPPjthka25pfKfz5YBBtKsh1lQM=,iv:dBWBeKsCp7FW4/CSsEX9YGB3JddHgMKBThl+Iza2mEs=,tag:vrvByGKQ6+8IyMJ3KUJ9YQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
