apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: main-ingress
  namespace: external-dns
spec:
  endpoints:
  - dnsName: "snap-ingress.${SECRET_DOMAIN}"
    recordTTL: 180
    recordType: A
    targets:
    - 10.172.90.80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kubernetes-dashboard
  namespace: external-dns
spec:
  endpoints:
  - dnsName: "snap-dash.${SECRET_DOMAIN}"
    recordTTL: 180
    recordType: CNAME
    targets:
    - "snap-ingress.${SECRET_DOMAIN}"