apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: main-ingress
  namespace: external-dns
spec:
  endpoints:
  - dnsName: "${INGRESS_HOST}"
    recordTTL: 180
    recordType: A
    targets:
    - "${INGRESS_IP}"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kubernetes-dashboard
  namespace: external-dns
spec:
  endpoints:
  - dnsName: "snap-dash.${SECRET_DOMAIN}"
    recordTTL: 180
    recordType: CNAME
    targets:
    - "${INGRESS_HOST}"