---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: influxdata-charts
  namespace: flux-system
spec:
  interval: 5m
  url: https://helm.influxdata.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app influxdb
  namespace: &ns storage
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system

  values:
    image:
      repository: influxdb
      tag: 2.7.5-alpine

    securityContext:
      fsGroupChangePolicy: "OnRootMismatch"

    pdb:
      create: false

    adminUser:
      organization: "homesys"
      user: "admin"
      bucket: "default"
      existingSecret: "influxdb-secrets"

    persistence:
      enabled: true
      useExisting: true
      name: local-influxdb

    ingress:
      enabled: true
      className: nginx
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Time Series DB
        gethomepage.dev/group: data
        gethomepage.dev/icon: influxdb.png
        gethomepage.dev/ping: 10.172.90.40
        gethomepage.dev/name: InfluxDB
      hostname: "influxdb.${SECRET_DOMAIN}"
      tls: true

    service:
      type: LoadBalancer
      loadBalancerIP: 10.172.90.40
