---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-influxdb
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/tera/vols/influxdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - elite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-influxdb
  namespace: system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: local-influxdb
