apiVersion: v1
kind: Secret
metadata:
    name: kopia-secrets
    namespace: system
stringData:
    KOPIA_USERNAME: ENC[AES256_GCM,data:DcrJTg==,iv:g037r1SxS2e9gCVnuUB/wjg9lQJQt1wLb/kby6CY5k0=,tag:gntXeFJ1+kZXILyqv+Q8OA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:lRPbFq6D1/VmRKKN9SyvdDBlvrk=,iv:fEGgEG3zRR6TozomeObDTA7vOm0JaAhIhuV1fU0IIC0=,tag:V8UUZTs9rNPxT2epoXnvfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WkhzRk9OUEVEMVZHS2hD
            ZnlGd3B2enJrSDVCaHp4b3hGWktWbGc4ejM0Cm1lMTN6NUh1OVRxMVNBUGM0N1J5
            TUpPN2o5K3A5Uld1NnBDNU5iUFUvUEkKLS0tIGEwTCtwL2tTNlVwQ0gwUEdZdVMv
            Umh5Z3lxQVJWOERtbVE4Y2hLclJjdkUKQsmn0Bjppm0k/FLSLowgS6nG+0aU1msI
            Qk64QcLJuEFBFcirvtEmPVMPMMz/Jhe9VgH0nlpcLEjcwg4dYvBHig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T00:27:32Z"
    mac: ENC[AES256_GCM,data:2zSRaiGt2FpEymgCCt//W6YKit6z1U+5OT7TLeAy3GTy2MeW6irCSDTIb/VnAfsLPbp3fsEgKxQzDu9agsiUXPW+F9onqf1oSykyKVumGftzZ4QLu7zIlShveQBLvzs40UK7K0H7fPsk63g+eX9z6vpnJhLHEPA/QZJ/aozmOZY=,iv:8gtCZfFL77Ti1OZ8gxUuyymqh06gpn3+sOYooE2fLoQ=,tag:ouZBVJDaONZfZYGWiriUQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
