---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./kopia-app.yaml
  - ./kopia-pvc.yaml
configMapGenerator:
  - name: kopia
    files:
      - repository.config
generatorOptions:
  disableNameSuffixHash: true