---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-gphotos
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/tera/vols/gphotos
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - elite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-gphotos
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: local-gphotos
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-chrome
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/tera/vols/gphotos
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - elite
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-chrome
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: local-chrome