apiVersion: v1
kind: Secret
metadata:
    name: production-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:5LYWb+AWdUqNqGuZ6hDPhZw=,iv:hiCSrn5l0K5qokU2nkDb0dhB9X5XcWCVoRT/agGLgk4=,tag:PU5QvqGz8A2KoMbxA0Sz/A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:138+nKYKs4R1fA==,iv:nl+8f87G1dAfY1xiuDj5gR3qnaCmDkPYrZG+svi+5ts=,tag:Q1CtWF2MCGkYa3ChRIBwxA==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:gBu2+JBwzL/jnxYTcMF8/NF1LDSbW99Vw4M3qhqruM3KxnvPm8o1AA==,iv:ZmYRwMKnwo5t+ChAMh9201YMF5egGFF8XzB8/CKzVh0=,tag:knbWXWr6lJ7NJGkzvPCp6w==,type:str]
    IP_RANGE: ENC[AES256_GCM,data:cti0tnt6ZdUo6mDwbq3XOHSAn7pRZ6XATQ==,iv:K0TEBLMxjwuBygH2CeYucP+TkX+m+1MitVsoSt/JwO4=,tag:fh69Oiz2xW4e40PVp4JGyQ==,type:str]
    INGRESS_IP: ENC[AES256_GCM,data:DwRKERgL1vPqZ1rh,iv:dgzZ3GHuBOJZqvuojtQp3ZcWcOuM393ytuirWwKKyE0=,tag:JUz11Q8lyr6EAsiaVPwbgA==,type:str]
    INGRESS_HOST: ENC[AES256_GCM,data:PEYUbvEFqLJpgcOcGSKcb4pr,iv:xM/ONFtKW+Lggg94vzo1hulqG9dItkZrNQkP8bFk8+Y=,tag:QznszXtgZ2g56+FZnf1IpA==,type:str]
    NAS_HOST: ENC[AES256_GCM,data:QK3mU/ry8nQd26E=,iv:jyvZN/X/eUzBCYpqoTQBGdLMlh5yuldk7LNBUvY3jR4=,tag:T2JLG8I1Qu5Wucwh8bBgLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p344yqccrc8c93qem34g7d99cwrdcjwjrd7l4vqw4ffalj8xcpgqxgethu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMVlLQ21DWHRnanFHVFZN
            YTN1amFBQzE1Zm5ham5WUTcyVDJIVmZ5WWdBCm0wa3RsczQ0dVZEUzVIbVVENWx6
            VmNLNzdrUFhnYXovMU1WNExkSTV4cW8KLS0tIEIvUjJmSGQ4N2Z0Z2J2VFBMdkJv
            RXFSZUV0VW54UjBaSlZETE1QOEVBMHMKwasostGOaTdX/u+mV56PxUGVbfKvveHJ
            hKPe2kw6CfMMPvuZWcV1gqWsGT1fIfh/xJskG+hfpQMwnrHNf8ln5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T06:42:14Z"
    mac: ENC[AES256_GCM,data:lHTVOQLnzc8o9nXZagUwaOSYZQS0KtSw68sB6x1oRN+amv4SmJgMkc16JFPPOjrNtz1cCcRaaJeOkzpySkiUdFaiAuGMjyW4EaxrGmJUXR7RqOtrEVxOU3VzAlX1/yXGOL+n2rRkWUCxAuN0PrJlkNILYwUcYI/lb7PDDYMDxNM=,iv:UzT2G42LczCIUJkyaI2LExBQdKqd6tcfC0Gbzee3kiY=,tag:SDnuH8/v6eEkWQN+OKcxRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
